In [1]:
import numpy as np

In [2]:
a = np.random.rand(1, 3)
b = np.random.rand(3, 3)
c = b * a
print(c)

[[0.0510398  0.60068205 0.60113561]
 [0.08205516 0.50758743 0.68621526]
 [0.01399649 0.40227372 0.41402762]]


In [7]:
x = np.random.rand(4, 5)

y = np.sum(x, axis=1)
y.shape

(4,)